"use client";
import {useState} from "react";
import {createClient} from "@/lib/supabase/client";
type Task={id:number;user_id:string;title:string;due_date:string|null;completed:boolean;created_at:string;updated_at:string};
export default function DashboardTasks({userId,initialTasks}:{userId:string;initialTasks:Task[]}){
 const s=createClient(),[tasks,setTasks]=useState(initialTasks),[title,setTitle]=useState(""),[due,setDue]=useState(""),[busy,setBusy]=useState(false);
 async function add(){if(!title.trim()||busy)return;setBusy(true);const{data,error}=await s.from("client_dashboard_tasks").insert({user_id:userId,title:title.trim(),due_date:due||null}).select("*").single();setBusy(false);if(error||!data){alert("Could not add that task. Please try again.");return}setTasks(v=>[...v,data].sort((a,b)=>(a.completed===b.completed?String(a.due_date||"9999").localeCompare(String(b.due_date||"9999")):Number(a.completed)-Number(b.completed)));setTitle("");setDue("")}
 async function toggle(t:Task){const next=!t.completed;const{data,error}=await s.from("client_dashboard_tasks").update({completed:next,updated_at:new Date().toISOString()}).eq("id",t.id).eq("user_id",userId).select("*").single();if(error||!data){alert("Could not update that task.");return}setTasks(v=>v.map(x=>x.id===t.id?data:x))}
 async function remove(t:Task){const{data,error}=await s.from("client_dashboard_tasks").delete().eq("id",t.id).eq("user_id",userId).select("id");if(error||!data?.length){alert("Could not delete that task.");return}setTasks(v=>v.filter(x=>x.id!==t.id))}
 return <div className="cp-card cp-dashboard-tasks"><div className="cp-section-head"><div><p className="cp-eyebrow">My tasks</p><h2>What do you need to get done?</h2><p className="cp-muted">Add anything here, even if it is not tied to a job.</p></div></div><div className="cp-task-add"><input className="cp-input" value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")add()}} placeholder="Add a task..." aria-label="Task"/><input className="cp-input cp-task-date" type="date" value={due} onChange={e=>setDue(e.target.value)} aria-label="Due date"/><button className="cp-button" disabled={busy||!title.trim()} onClick={add}>{busy?"Adding...":"+ Add task"}</button></div><div className="cp-task-list">{tasks.length?tasks.map(t=><div className={"cp-task-row"+(t.completed?" completed":"")} key={t.id}><button className="cp-task-check" onClick={()=>toggle(t)} aria-label={t.completed?"Mark incomplete":"Mark complete"}>{t.completed?"Done":""}</button><div className="cp-task-copy"><strong>{t.title}</strong>{t.due_date?<small>Due {new Date(t.due_date+"T12:00:00").toLocaleDateString("en-US",{month:"short",day:"numeric"})}</small>:null}</div><button className="cp-task-delete" onClick={()=>remove(t)} aria-label="Delete task">Delete</button></div>):<div className="cp-task-empty">No personal tasks yet. Add one above.</div>}</div></div>
}