import Link from"next/link";import{redirect}from"next/navigation";import{createClient}from"@/lib/supabase/server";import DailyActions from"./DailyActions";import MessageTemplates from"./MessageTemplates";
export const dynamic="force-dynamic";const fmt=(d:string)=>new Date(`${d}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric"});
export default async function Page(){const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)redirect("/client-portal/login");await Promise.all([s.rpc("claim_jgo_client_portal"),s.rpc("claim_member_entitlements")]);const[{data:client},{data:entitlements}]=await Promise.all([s.from("clients").select("id,name,email,next_step,due_date,portal_coach_focus").eq("portal_user_id",user.id).order("id",{ascending:false}).limit(1).maybeSingle(),s.from("member_entitlements").select("entitlement").eq("user_id",user.id)]);const hasGuide=(entitlements??[]).some(e=>e.entitlement==="linkedin_guide");if(!client)return <main className="cp-main cp-home"><div className="cp-shell">
<section className="cp-home-hero"><div><p className="cp-eyebrow">Your JGO workspace</p><h1 className="cp-title">Hi, {first}.</h1><p className="cp-subtitle">Your job search, organized in one place.</p></div><Link className="cp-button" href="/client-portal/jobs">+ Add a job</Link></section>
{latestAccepted?<section className="cp-celebrate"><strong>You did it! Congratulations!</strong><span>You landed the role{latestAccepted.company?` at ${latestAccepted.company}`:""}. That is something to celebrate.</span></section>:offers>0?<section className="cp-celebrate"><strong>You have {offers===1?"an offer":"offers"}!</strong><span>Keep your tracker updated while you evaluate next steps.</span></section>:null}
<section className="cp-home-primary">
  <div className="cp-home-today"><DailyActions actions={actions} completedKeys={(completed??[]).map(x=>x.action_key)}/></div>
  <div className="cp-home-focus"><p className="cp-eyebrow">Coach focus</p><h2>{client.portal_coach_focus||client.next_step||"Keep your momentum going"}</h2><p className="cp-muted">{client.due_date?`Target date: ${fmt(client.due_date)}`:"Your main priority right now."}</p><Link className="cp-link" href="/client-portal/jobs">Open tracker →</Link></div>
</section>
<section className="cp-home-snapshot">
  <div><strong>{active}</strong><span>Active</span></div><div><strong>{submitted}</strong><span>Applied</span></div><div><strong>{interviewing}</strong><span>Interviewing</span></div><div><strong>{offers}</strong><span>Offers</span></div>
</section>
<section className="cp-section"><div className="cp-section-head"><div><p className="cp-eyebrow">Workspace</p><h2>Everything you need</h2></div></div><div className="cp-home-nav-grid">
<Link className="cp-home-nav-card" href="/client-portal/jobs"><span className="cp-home-nav-icon">JT</span><div><h3>Job Tracker</h3><p>Jobs, contacts, follow-ups and interviews.</p></div><span>›</span></Link>
<a className="cp-home-nav-card" href="#message-templates"><span className="cp-home-nav-icon">MT</span><div><h3>Message Templates</h3><p>Customize outreach and save your own.</p></div><span>↓</span></a>
<Link className="cp-home-nav-card" href="/client-portal/files"><span className="cp-home-nav-icon">DOC</span><div><h3>Documents</h3><p>Coach files and documents for review.</p></div><span>›</span></Link>
<Link className="cp-home-nav-card" href="/client-portal/resources"><span className="cp-home-nav-icon">JGO</span><div><h3>Resources</h3><p>CORE, Interview Ready and client tools.</p></div><span>›</span></Link>
</div></section>
{interviews.length?<section className="cp-section cp-home-interviews"><div className="cp-section-head"><div><p className="cp-eyebrow">Coming up</p><h2>Upcoming interviews</h2></div></div><div className="cp-grid cp-grid-3">{interviews.map(j=><div className="cp-card cp-interview-card" key={j.id}><span className="cp-badge">{fmt(j.interview_date!)}</span><h3>{j.company||"Interview"}</h3><p className="cp-muted">{j.job_title||j.status}</p><div className="cp-interview-actions"><Link className="cp-button" href="/client-portal/resources/core-framework">Prep with CORE</Link><Link className="cp-link" href="/client-portal/jobs">View job</Link></div></div>)}</div></section>:null}
<section id="message-templates" className="cp-section cp-home-templates"><MessageTemplates userId={user.id} initialTemplates={messageTemplates??[]}/></section>
{hasGuide?<section className="cp-section"><Link className="cp-home-guide" href="/course"><div><p className="cp-eyebrow">Included resource</p><h3>LinkedIn Optimization Guide</h3><p>Continue your guide anytime.</p></div><span>Open guide →</span></Link></section>:null}
</div></main>}}