"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase/client";

type Contact={id?:number;job_id?:number;name:string;title:string|null;email:string|null;phone:string|null;contact_type:string|null;notes:string|null};
type Job={id:number;company:string;job_title:string;status:string;date_applied:string|null;next_step:string|null;next_step_date:string|null;job_url:string|null;location:string|null;source:string|null;salary:string|null;compensation:string|null;remote_type:string|null;priority:string|null;recruiter_name:string|null;recruiter_email:string|null;recruiter_phone:string|null;last_contacted_at:string|null;follow_up_date:string|null;notes:string|null;client_job_contacts?:Contact[]};
const statuses=["Open / Interested","Application Submitted","Messaged Contact","Recruiter Screen","Interviewing","Final Interview","Offer","Rejected","Withdrawn","Closed"];
const interviewStatuses=["Recruiter Screen","Interviewing","Final Interview"];
type SaveState="idle"|"saving"|"saved"|"error";
function statusTone(s:string){if(s==="Offer")return"bg-[#dcebd9] text-[#38563a]";if(interviewStatuses.includes(s))return"bg-[#e8e6f3] text-[#555078]";if(["Rejected","Withdrawn","Closed"].includes(s))return"bg-[#f2e8e5] text-[#8a5f58]";if(s==="Application Submitted")return"bg-[#e5edf2] text-[#4c6878]";if(s==="Messaged Contact")return"bg-[#f4ecd9] text-[#75613d]";return"bg-[#eef1e9] text-[#61705d]"}
export default function JobsPage(){const supabase=createClient();const[jobs,setJobs]=useState<Job[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[filter,setFilter]=useState("All"),[saving,setSaving]=useState<Record<number,SaveState>>({}),[expanded,setExpanded]=useState<Record<number,boolean>>({});
 async function load(){const{data}=await supabase.from("client_job_applications").select("*,client_job_contacts(*)").order("updated_at",{ascending:false});setJobs((data as Job[])||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function add(){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data,error}=await supabase.from("client_job_applications").insert({user_id:user.id,company:"",job_title:"",status:"Open / Interested"}).select("*,client_job_contacts(*)").single();if(!error&&data){setJobs(v=>[data as Job,...v]);setExpanded(v=>({...v,[data.id]:true}))}}
 function local(id:number,field:keyof Job,value:string){setJobs(v=>v.map(j=>j.id===id?{...j,[field]:value}:j))}
 async function persist(id:number,field:keyof Job,value:string){setSaving(v=>({...v,[id]:"saving"}));const{error}=await supabase.from("client_job_applications").update({[field]:value||null,updated_at:new Date().toISOString()}).eq("id",id);setSaving(v=>({...v,[id]:error?"error":"saved"}));if(!error)setTimeout(()=>setSaving(v=>({...v,[id]:"idle"})),1000)}
 async function addContact(jobId:number){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data}=await supabase.from("client_job_contacts").insert({job_id:jobId,user_id:user.id,name:"New Contact",contact_type:"Contact"}).select("*").single();if(data)setJobs(v=>v.map(j=>j.id===jobId?{...j,client_job_contacts:[...(j.client_job_contacts||[]),data as Contact]}:j))}
 function contactLocal(jobId:number,index:number,key:keyof Contact,value:string){setJobs(v=>v.map(j=>j.id===jobId?{...j,client_job_contacts:(j.client_job_contacts||[]).map((c,i)=>i===index?{...c,[key]:value}:c)}:j))}
 async function saveContact(jobId:number,index:number,key:keyof Contact,value:string){const c=jobs.find(j=>j.id===jobId)?.client_job_contacts?.[index];if(c?.id)await supabase.from("client_job_contacts").update({[key]:value||null}).eq("id",c.id)}
 async function deleteContact(jobId:number,index:number){const c=jobs.find(j=>j.id===jobId)?.client_job_contacts?.[index];if(c?.id)await supabase.from("client_job_contacts").delete().eq("id",c.id);setJobs(v=>v.map(j=>j.id===jobId?{...j,client_job_contacts:(j.client_job_contacts||[]).filter((_,i)=>i!==index)}:j))}
 async function remove(id:number){if(!confirm("Delete this job from your tracker?"))return;const{error}=await supabase.from("client_job_applications").delete().eq("id",id);if(!error)setJobs(v=>v.filter(j=>j.id!==id))}
 const visible=useMemo(()=>jobs.filter(j=>{const q=search.toLowerCase();return(!q||`${j.company} ${j.job_title} ${j.recruiter_name||""} ${j.notes||""}`.toLowerCase().includes(q))&&(filter==="All"||j.status===filter)}),[jobs,search,filter]);
 const submitted=jobs.filter(j=>!["Open / Interested","Rejected","Withdrawn","Closed"].includes(j.status)).length,interviews=jobs.filter(j=>interviewStatuses.includes(j.status)).length,offers=jobs.filter(j=>j.status==="Offer").length,contacts=jobs.filter(j=>j.status==="Messaged Contact").length;
 const input=(j:Job,key:keyof Job,p:string,type="text")=><input type={type} value={String(j[key]??"")} onChange={e=>local(j.id,key,e.target.value)} onBlur={e=>persist(j.id,key,e.target.value)} placeholder={p} className="mt-1 w-full rounded-xl border border-[#ddd9d1] bg-white px-3 py-2.5 text-sm font-normal normal-case outline-none focus:border-[#91a18b]"/>;
 return <main className="min-h-screen bg-[#f7f5f0] text-[#223028]"><div className="mx-auto max-w-[1400px] px-4 pb-20 sm:px-6 lg:px-8"><header className="sticky top-0 z-20 -mx-4 flex items-center justify-between border-b border-[#e1ddd5] bg-[#f7f5f0]/95 px-4 py-4 backdrop-blur sm:-mx-6 sm:px-6"><Link href="/portal" className="font-serif text-xl">JGO Hire <span className="ml-2 text-[10px] font-bold uppercase tracking-widest text-[#7a847c]">Member Portal</span></Link><Link href="/portal" className="rounded-xl border bg-white px-4 py-2 text-sm font-bold text-[#4f6449]">Portal Home</Link></header>
<section className="pt-10"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#708267]">Your job search command center</p><h1 className="mt-2 font-serif text-5xl">Job Tracker</h1><p className="mt-3 max-w-2xl leading-7 text-[#68746a]">Add a role in seconds, then keep every application, recruiter, contact, interview, and follow-up in one place.</p></div><button onClick={add} className="rounded-xl bg-[#52684d] px-6 py-3.5 text-sm font-black text-white">+ Add opportunity</button></div>
<div className="mt-7 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Applications out",submitted,"submitted or beyond"],["Contacts messaged",contacts,"networking in motion"],["Interviewing",interviews,"active interviews"],["Offers",offers,"offer stage"]].map(([l,n,s])=><div key={String(l)} className="rounded-[22px] border border-[#e2ded6] bg-white p-5 shadow-sm"><p className="text-[10px] font-black uppercase tracking-wider text-[#7d877e]">{l}</p><p className="mt-2 text-4xl font-black">{n}</p><p className="mt-1 text-xs text-[#929991]">{s}</p></div>)}</div>
<div className="mt-6 flex gap-3 rounded-2xl border border-[#e2ded6] bg-white p-3"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search company, role, recruiter or notes..." className="min-w-0 flex-1 rounded-xl border px-4 py-3 text-sm"/><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border bg-white px-4 text-sm font-bold"><option>All</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div>
{!loading&&!jobs.length?<div className="mt-6 rounded-[28px] border border-[#d8dfd4] bg-[#eef2eb] p-10 text-center"><h2 className="font-serif text-3xl">Add your first opportunity.</h2><p className="mt-2 text-[#667168]">You only need the company and job title to start. Add everything else when you have it.</p><button onClick={add} className="mt-5 rounded-xl bg-[#52684d] px-5 py-3 font-bold text-white">+ Add opportunity</button></div>:null}
<div className="mt-6 space-y-4">{visible.map(j=><article key={j.id} className="rounded-[26px] border border-[#e0dcd4] bg-white p-5 shadow-sm"><div className="grid gap-3 lg:grid-cols-[1fr_1fr_220px_auto]"><input value={j.company} onChange={e=>local(j.id,"company",e.target.value)} onBlur={e=>persist(j.id,"company",e.target.value)} placeholder="Company" className="rounded-xl border px-4 py-3 font-serif text-xl outline-none"/><input value={j.job_title} onChange={e=>local(j.id,"job_title",e.target.value)} onBlur={e=>persist(j.id,"job_title",e.target.value)} placeholder="Job title" className="rounded-xl border px-4 py-3 text-sm outline-none"/><select value={j.status} onChange={e=>{local(j.id,"status",e.target.value);persist(j.id,"status",e.target.value)}} className={`rounded-xl border-0 px-4 py-3 text-xs font-black ${statusTone(j.status)}`}>{statuses.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>setExpanded(v=>({...v,[j.id]:!v[j.id]}))} className="rounded-xl border px-4 py-3 text-sm font-bold text-[#52684d]">{expanded[j.id]?"Close":"Details"}</button></div>
<div className="mt-3 grid gap-3 sm:grid-cols-[1fr_180px]"><label className="text-[10px] font-black uppercase tracking-wider text-[#7a847c]">Job posting URL{input(j,"job_url","Paste job link here")}</label><label className="text-[10px] font-black uppercase tracking-wider text-[#7a847c]">Date applied{input(j,"date_applied","","date")}</label></div>
{expanded[j.id]?<div className="mt-5 border-t border-[#eeeae2] pt-5"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><label className="text-[10px] font-black uppercase tracking-wider text-[#7a847c]">Location{input(j,"location","City / Remote")}</label><label className="text-[10px] font-black uppercase tracking-wider text-[#7a847c]">Source{input(j,"source","LinkedIn, referral...")}</label><label className="text-[10px] font-black uppercase tracking-wider text-[#7a847c]">Compensation{input(j,"compensation","$120k-$140k")}</label><label className="text-[10px] font-black uppercase tracking-wider text-[#7a847c]">Priority<select value={j.priority||"Medium"} onChange={e=>{local(j.id,"priority",e.target.value);persist(j.id,"priority",e.target.value)}} className="mt-1 w-full rounded-xl border bg-white px-3 py-2.5 text-sm font-normal normal-case"><option>High</option><option>Medium</option><option>Low</option></select></label></div>
<div className="mt-6 rounded-[22px] bg-[#f6f7f3] p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-wider text-[#708267]">Recruiter</p><h3 className="font-serif text-xl">Primary recruiter</h3></div></div><div className="mt-3 grid gap-3 md:grid-cols-3">{input(j,"recruiter_name","Recruiter name")}{input(j,"recruiter_email","Email","email")}{input(j,"recruiter_phone","Phone","tel")}</div></div>
<div className="mt-5 rounded-[22px] border p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-wider text-[#708267]">People</p><h3 className="font-serif text-xl">Additional contacts</h3></div><button onClick={()=>addContact(j.id)} className="rounded-lg bg-[#edf2e9] px-3 py-2 text-xs font-black text-[#52684d]">+ Add contact</button></div><div className="mt-4 space-y-3">{(j.client_job_contacts||[]).map((c,i)=><div key={c.id||i} className="grid gap-2 rounded-xl bg-[#faf9f6] p-3 md:grid-cols-5"><input value={c.name} onChange={e=>contactLocal(j.id,i,"name",e.target.value)} onBlur={e=>saveContact(j.id,i,"name",e.target.value)} placeholder="Name" className="rounded-lg border px-3 py-2 text-sm"/><input value={c.title||""} onChange={e=>contactLocal(j.id,i,"title",e.target.value)} onBlur={e=>saveContact(j.id,i,"title",e.target.value)} placeholder="Title / relationship" className="rounded-lg border px-3 py-2 text-sm"/><input value={c.email||""} onChange={e=>contactLocal(j.id,i,"email",e.target.value)} onBlur={e=>saveContact(j.id,i,"email",e.target.value)} placeholder="Email" className="rounded-lg border px-3 py-2 text-sm"/><input value={c.phone||""} onChange={e=>contactLocal(j.id,i,"phone",e.target.value)} onBlur={e=>saveContact(j.id,i,"phone",e.target.value)} placeholder="Phone" className="rounded-lg border px-3 py-2 text-sm"/><button onClick={()=>deleteContact(j.id,i)} className="text-xs font-bold text-[#9a665f]">Remove</button></div>)}</div></div>
<div className="mt-5 grid gap-4 md:grid-cols-3"><label className="text-[10px] font-black uppercase tracking-wider text-[#7a847c]">Next step{input(j,"next_step","Follow up, interview...")}</label><label className="text-[10px] font-black uppercase tracking-wider text-[#7a847c]">Next step date{input(j,"next_step_date","","date")}</label><label className="text-[10px] font-black uppercase tracking-wider text-[#7a847c]">Follow-up date{input(j,"follow_up_date","","date")}</label></div><label className="mt-4 block text-[10px] font-black uppercase tracking-wider text-[#7a847c]">Additional notes<textarea value={j.notes||""} onChange={e=>local(j.id,"notes",e.target.value)} onBlur={e=>persist(j.id,"notes",e.target.value)} placeholder="Interview notes, referral details, reminders, context..." rows={4} className="mt-1 w-full rounded-xl border px-3 py-3 text-sm font-normal normal-case"/></label></div>:null}
<div className="mt-4 flex justify-between border-t pt-4 text-xs"><span className="font-bold text-[#748075]">{saving[j.id]==="saving"?"Saving...":saving[j.id]==="saved"?"Saved":"Changes save automatically"}</span><button onClick={()=>remove(j.id)} className="font-bold text-[#9a665f]">Delete opportunity</button></div></article>)}</div></section></div></main>}
