import s from "./JgoJobLaunch.module.css";
export default function JgoJobLaunch(){
 return <section className={s.section} aria-labelledby="jgojob-product-title"><div className={s.shell}>
  <div className={s.heading}><p className={s.eyebrow}>MEET JGO JOB</p><h2 id="jgojob-product-title">Your job search finally has a home.</h2><p>Built by a recruiter and career coach to keep the part after “apply” from becoming chaos.</p></div>
  <div className={s.stage}>
   <div className={s.copy}><span className={s.pill}>New from JGO Hire · Free for a limited time</span><h3>I built the job tracker I wish candidates had.</h3><p>Keep the role, people, outreach, interviews, follow-ups and next move connected in one organized place.</p><div className={s.chips}><span>Jobs</span><span>People</span><span>Interviews</span><span>Tasks</span><span>Notes</span></div><a className={s.cta} href="https://jgojob.com/?utm_source=jgohire&utm_medium=website&utm_campaign=jgojob_launch&utm_content=homepage">Start your free tracker →</a><small>No credit card required.</small></div>
   <div className={s.app} aria-label="Preview of JGO Job"><div className={s.top}><div className={s.logo}>J</div><b>JGO JOB</b><span>JOB TRACKER</span></div><div className={s.hero}><small>YOUR SEARCH</small><strong>Let’s keep this organized.</strong><p>Everything connected to your next opportunity, in one place.</p></div><div className={s.stats}><div><small>ALL JOBS</small><b>8</b></div><div><small>APPLIED</small><b>4</b></div><div><small>INTERVIEWS</small><b>2</b></div></div><div className={s.job}><span><i></i><b>Senior Marketing Manager</b><small>Acme · Applied</small></span><em>Next: Follow up Friday →</em></div><div className={s.job}><span><i></i><b>Communications Lead</b><small>North & Co. · Interview</small></span><em>Prep interview →</em></div></div>
  </div>
 </div></section>
}