"use client";

import Link from "next/link";
import Image from "next/image";
import { useMemo, useState } from "react";
import "./open-to-work.css";

const steps = [
  { title: "Why Open to Work Matters", eyebrow: "Step 1", content: (<>
    <div className="otw-image"><Image src="/course/open-to-work.png" alt="LinkedIn Open to Work example" width={1200} height={675} priority/></div>
    <div className="otw-reading-card"><p>Open to Work is a LinkedIn setting that signals to recruiters that you are available and open to new opportunities.</p></div>
    <aside className="otw-statement-card"><span>Open to Work Rule</span><p>If you are actively looking for a new position, turn on “Open to Work”. It actually helps.</p></aside>
  </>) },
  { title: "How to Turn It On", eyebrow: "Step 2", content: (<section className="otw-howto-card"><div className="otw-howto-header"><span>How To Edit</span><strong>Turn on Open to Work</strong></div><div className="otw-howto-body"><div><span>01</span><p>To turn it on, click the "Open to" button near the top of your profile and select "Finding a new job."</p></div><div><span>02</span><p>From there you will fill out the types of roles you are looking for, your preferred location and work setting, and when you are available to start.</p></div></div></section>) },
  { title: "Who Can See It", eyebrow: "Step 3", content: (<>
    <div className="otw-reading-card"><p>When setting this up, you will be asked who can see that you are open to work.</p><p>If you select everyone, a green semicircle with the words "Open to Work" will appear around your profile photo. Anyone who visits your profile can see it.</p><p>If you select recruiters only, the banner does not show on your photo at all. It is only visible on the backend when a recruiter is actively searching using LinkedIn Recruiter. This is important to understand: LinkedIn Recruiter is a paid platform that companies subscribe to. Just because someone has the word "recruiter" in their title does not mean they have access to it. However, most agency and corporate recruiters who are actively sourcing candidates do use it, so it is safe to assume that recruiters in the traditional sense will be able to see your status.</p></div>
    <div className="otw-choice-grid"><article><span>01</span><h3>Everyone</h3><p>If you select everyone, a green semicircle with the words "Open to Work" will appear around your profile photo. Anyone who visits your profile can see it.</p></article><article><span>02</span><h3>Recruiters Only</h3><p>If you select recruiters only, the banner does not show on your photo at all. It is only visible on the backend when a recruiter is actively searching using LinkedIn Recruiter.</p></article></div>
  </>) },
  { title: "Important Context", eyebrow: "Step 4", content: (<aside className="otw-dark-card"><span>Important Context</span><h3>It is a reasonable layer of protection, but go in with eyes open.</h3><p>This setting is also how LinkedIn attempts to hide your Open to Work status from your current employer. If your company does not have a LinkedIn Recruiter license, they will not see it. That said, it is not a perfect system. If someone at your company happens to have recruiter access, or if a colleague visits your profile directly, there is no guarantee. It is a reasonable layer of protection, but go in with eyes open.</p><p>We will get into how the green “Open to Work” banner is perceived in a moment, but keep this choice in mind as you go through the setup.</p></aside>) },
  { title: "Why This Matters", eyebrow: "Step 5", content: (<div className="otw-reading-card"><p>If you are actively looking for a new position, turn on “Open to Work”. It actually helps.</p><p>This is not the same as writing "open to work" in your headline, or placing the green “open to work” banner on your profile photo. This is a backend setting that recruiters can see when they are searching. When this setting is on, you show up more in results and recruiters immediately know you are open to a conversation. That alone can make a difference.</p><p>Do not turn it on and leave it half filled out. Actually complete it.</p></div>) },
  { title: "Job Titles", eyebrow: "Step 6", content: (<>
    <div className="otw-reading-card"><p>Be specific. This is not the place to list ten different things that do not relate to each other. Pick the roles you are actually targeting and keep it focused. If you are going for software engineering roles, put that. If you are targeting business analyst roles, put that. Make it make sense.</p><p>If you are not sure what to include, use AI to help.</p></div>
    <aside className="otw-prompt-card"><div className="otw-prompt-top"><div><span>Copy + Paste Prompt</span><h3>Choose the right job titles.</h3></div><small>AI Tool Ready</small></div><div className="otw-prompt-body"><p>Based on my experience and the roles I am targeting in [INSERT ROLES AND INDUSTRY], suggest 5 to 8 specific job titles I should use in my LinkedIn Open to Work settings. Keep them realistic, aligned with my background, and commonly searched by recruiters. Do not include anything unrelated or overly broad.</p><p>[PASTE EXPERIENCE]</p></div></aside>
    <aside className="otw-tip-card"><span>Reminder</span><p>Then go through the list and only keep what actually fits you.</p></aside>
  </>) },
  { title: "Location", eyebrow: "Step 7", content: (<div className="otw-reading-card"><p>Your location should match where you are actually applying. If you are open to relocating, include those cities. If you are only looking locally, keep it to that. Make sure it lines up with your profile and your applications.</p></div>) },
  { title: "Work Type and Details", eyebrow: "Step 8", content: (<div className="otw-reading-card"><p>Be honest. If you only want remote, put remote. Do not check every box just to get more visibility if you are not actually open to those options. The same goes for employment type and start date. Fill it out based on your real situation.</p><p>That said, do not treat this as set in stone. Recruiters are not relying on this alone and may still reach out with something slightly outside what you selected. You might also find yourself more flexible depending on the role. Use it as a guide, not a hard rule.</p></div>) },
  { title: "The Green Banner", eyebrow: "Step 9", content: (<div className="otw-reading-card"><p>You are going to hear different opinions on this. Some recruiters think it looks desperate. Personally I think that is a little harsh. People need jobs, layoffs happen, and life is not always perfectly timed. But not everyone sees it that way.</p><p>If you want maximum visibility, use it. If you would rather keep things low key, turn on the recruiters only setting and skip the banner. There is no right answer. Just know how it can be perceived and make the decision that works for you.</p></div>) },
  { title: "Final Takeaway", eyebrow: "Step 10", content: (<aside className="otw-final-card"><span>Final Takeaway</span><h3>Make sure your profile actually reflects that.</h3><p>If you are open to work, make sure your profile actually reflects that. It helps more than most people realize.</p></aside>) },
];

export default function OpenToWorkLesson() {
  const [activeStep, setActiveStep] = useState(0);
  const progress = useMemo(() => Math.round(((activeStep + 1) / steps.length) * 100), [activeStep]);
  const currentStep = steps[activeStep];
  function moveToStep(index: number) { setActiveStep(index); window.scrollTo({ top: 0, behavior: "smooth" }); }
  return (<section className="otw-course"><div className="otw-topbar"><div><span>Open to Work Progress</span><strong>{progress}%</strong></div><div className="otw-progress"><span style={{ width: `${progress}%` }}/></div><span>Step {activeStep + 1} of {steps.length}</span></div><div className="otw-layout"><aside className="otw-steps">{steps.map((step,index)=><button type="button" key={step.title} className={index===activeStep?"otw-step otw-step-active":"otw-step"} onClick={()=>moveToStep(index)}><span>{String(index+1).padStart(2,"0")}</span><p>{step.title}</p></button>)}</aside><article className="otw-content"><div className="otw-heading"><p>{currentStep.eyebrow}</p><h2>{currentStep.title}</h2></div><div className="otw-body">{currentStep.content}</div><div className="otw-controls"><button type="button" onClick={()=>moveToStep(Math.max(0,activeStep-1))} disabled={activeStep===0}>← Previous</button>{activeStep===steps.length-1?<Link href="/course/connections" className="otw-next-lesson-card"><span><small>Next Lesson</small><strong>Connections</strong></span><span aria-hidden="true">→</span></Link>:<button type="button" onClick={()=>moveToStep(activeStep+1)}>Continue →</button>}</div></article></div></section>);
}
